[feat] todo 목록 재정렬하는 API 구현
sujeong11/on-boarding pull request #10
Opened 2024-02-18 12:57 UTC by sujeong11

## 🗃 요구사항
- 사용자는 할 일의 정렬 순서를 변경할 수 있습니다. (즉, 순서 데이터는 변경될 수 있습니다.)
- 사용자가 할 일의 순서를 변경하면 나머지 할 일들도 재정렬됩니다.
    - 즉 할 일 1, 2, 3, 4가 있을 때 할 일4를 두 번째로 옮기면 할 일 2, 3은 각각 할 일 3, 4가 됩니다.

## 🔥 Task
- 토큰 관련 에러 해결
- todo 재정렬하는 API 구현
- todo 재정렬하는 API 테스트 코드 작성

2024-02-19 01:16 UTC, mongmeo-dev requested changes
수고하셨습니다~ 리뷰 확인해주세요~!

2024-02-19 01:16 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +	}
계속 path 이야기를 하게 되는 것 같아 죄송할 따름입니다...
restful에서는 path로 행위를 표현하지 않아요~
`PATCH /api/v1/todos/{todoId}`로 패스를 잡고 해보세요~!

2024-02-19 01:16 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +	}
요렇게 구현하면 update문이 꽤 많이 나가지 않나유??

2024-02-19 01:16 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/entity/Todo.java
> +	}
0까지 떨어지지 않도록 방어해주세요~

2024-02-19 01:16 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/repository/TodoRepository.java
> +	List<Todo> findTodoBetweenOrders(@Param("memberId") Long memberId, @Param("start") int start, @Param("end") int end);
나중에 Lyrics 만들 때는 QueryDsl 사용해도 괜찮을 것 같아요~

2024-02-19 09:40 UTC, sujeong11 commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +	}
제가 restful한 url 작성법에 대해 더 자세하게 공부해서 리뷰 남기시지 않도록 해보겠습니다! 코멘트 감사드립니다!🙂

2024-02-20 21:35 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +	@PatchMapping("/{todoId}/reordering")
path에서 `reordering`이라는 컨텍스트를 굳이 가져갈 필요는 없어요~
말이 재정렬이지 결국에는 todo 정보 수정임을 생각하며 작업해주세요~

2024-02-21 02:39 UTC, sujeong11 commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +	@PatchMapping("/{todoId}/reordering")
path에 reordering를 빼면 기존에 있는 todo 수정 API과 path가 동일해집니다.. 그럼 기존에 있는 todo 수정 API와 함께 처리해야 할까요ㅠ??

2024-02-22 05:42 UTC, mongmeo-dev approved these changes
수고하셨습니다~!

2024-02-22 13:42 UTC, merged