[feat] 할 일과 관련된 CRUD API 구현
sujeong11/on-boarding pull request #7
Opened 2024-02-16 17:03 UTC by sujeong11

## 🗃 요구사항
- 사용자는 해야 할 일을 조회/추가/수정/삭제 할 수 있습니다.
- 해야 할 일에 들어갈 데이터는 다음과 같습니다.
    - 타이틀(Required)
    - 순서(Required)
    - 완료 여부(Required)
    - 메모(Optional)
 - 사용자는 할 일을 삭제할 수 있고, 삭제된 할 일은 휴지통에 저장됩니다.
- 사용자는 휴지통에 있는 할 일을 조회할 수 있고, 완전 삭제 혹은 복구가 가능합니다.
- 할 일 목록은 페이지네이션되어 조회됩니다. 단, 페이지 번호가 아닌 무한 스크롤 형식으로 구현하여야 합니다.

## 🔥 Task
- todo 엔티티 생성
- todo 생성 API 구현
- todo 수정 API 구현
- todo 단건 조회 API 구현
- todo 전체 조회 API 구현
  - [ 무한스크롤 동작 방식 ]
  - 프론트로부터 필요한 todo의 첫 id와 데이터 개수를 입력받는다. 
  - 그리고 첫 id로부터 데이터 개수를 조회하고 남은 데이터가 있는지 `hasNext` 값과 함께 반환한다.
- todo 삭제 API 구현
- 삭제한 todo 복구 API 구현
- 삭제된 todo 단건 조회 API 구현
- 삭제된 todo 전체 조회 API 구현

2024-02-17 08:21 UTC, mongmeo-dev requested changes
리뷰 확인해주세요 ~!

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +		Slice<Todo> todoList = todoRepository.findNotDeletedTodoAll(startTodoId, pageable);
정렬 순서 기준으로 정렬이 되어야 할 것 같아요~

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +	@GetMapping("/deleted")
(이건 개인 취향이니 수정하지 않으셔도 좋아요)
요 path들은 HTTP method와 path만으로 리소스가 리스트인지 아닌지 구분하기가 힘들어보여요!
삭제된 할 일 단 건 조회 시에는 삭제된 것과 그렇지 않은 것을 구분하지 않고, 리스트 조회 시에는 "/api/v1/todos?status=deleted"정도로 받아도 좋을 것 같아요~!

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +@RequestMapping("/api/v1/todo")
(개인 취향이니 수정하지 않으셔도 됩니다)
List path는 suffix로 -s를 붙여주시면 좋아요~!

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +	@DeleteMapping("/hard/{todoId}")
(이건 개인 취향이니 수정하지 않으셔도 좋아요)
자연스럽게 요 path들에 대해서도 수정의 여지가 있겠죠??!
물론 restful을 의도하지 않으셨다면(정확히는 HTTP method + path만으로 리소스를 표현할 의도가 없으셨다면) 여기에 남긴 제 path에 관한 리뷰는 모두 잘못된 리뷰입니당

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/entity/Todo.java
> +	private boolean isDeleted;
아마도 요 친구들을 위해서 `@DynamicInsert`를 사용하신 것 같은데, 맞을까요?
(그냥 궁금해서 여쭤봅니다! 저 어노테이션을 써본적이 없어서요!!)

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +		Pageable pageable = PageRequest.of(0, size);
offset 조건이 포함되지 않으니 pageable을 굳이 사용하지 않아도 될 것 같아요~!

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +		}
지속적으로 나오는 코드 같은데, 메서드로 빼주면 좋을 것 같아요~

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +			.collect(Collectors.toUnmodifiableList());
요 줄은 `.toList()`로 바꿔 써도 좋아요~!

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +		}
요 친구는 todo 객체의 메서드로 빼도 좋을 것 같네요 :)

2024-02-17 08:21 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/global/exception/ErrorCode.java
> +	TODO_MEMBER_ID_NOT_MATCH(1401, "해당 사용자가 작성한 할 일이 아닙니다.", HttpStatus.BAD_REQUEST),
요 친구는 403응답이 나가도 좋을 것 같아요 :)

2024-02-17 11:03 UTC, sujeong11 commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +		Pageable pageable = PageRequest.of(0, size);
저는 limit 값을 주기 위해 pagable를 사용했는데 올바른 방법이 아니라면 말씀해주세요!

2024-02-17 11:03 UTC, sujeong11 commented on src/main/java/com/projectlyrics/onboarding/domain/todo/entity/Todo.java
> +	private boolean isDeleted;
넵 맞습니다!
(지금 보니, @DynamicInsert가 아닌 `@DynamicUpdate`를 사용을 의도했는데 수정이 필요할 것 같습니다ㅠ..)
Todo 테이블은 위 2개의 컬럼이 자주 수정될 것 같다고 생각했습니다! 그래서 @DynamicUpdate를 붙여 전체 컬럼을 수정하는 쿼리문이 아닌 수정된 컬럼만 수정하는 컬럼이 실행되게 하여 쿼리 실행 속도를 높이고자 사용했습니당

2024-02-18 01:29 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/service/TodoService.java
> +		Pageable pageable = PageRequest.of(0, size);
사실 이런 건 정답이 없어요! 뭐가 맞다 틀리다의 문제는 아니고, 그냥 취향차이 같아요~!
저는 개인적으로 웬만하면 Spring 자체에 대한 의존성을 줄이는 것을 더 좋아하는 편이라 말씀드린 건데, 있는 기능 쓰는 게 잘못된 건 아니니까요~

2024-02-18 01:35 UTC, mongmeo-dev reviewed
마지막으로 딱 하나만...! 확인해주세요~!(물론 이건 강제가 아니지만, restful이라고 써두셨길래...!적어봅니당)

2024-02-18 01:35 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +	@PostMapping("/todo")
엇 제가 말씀 드린 것은 요런 뜻이 아니었어요!!
아래의 단일 Get도 그렇지만, 음...쉽게 말해 path가 폴더 구조라고 생각하시면 좋을 것 같아요~!
요 메서드의 경우 `POST /api/v1/todos`가 되는 것이 일반적인데, todo들이 들어있는 폴더(`todos/`)에 새로운 todo를 추가할거야! 정도의 패스로 생각해주시면 좋아요 :)
아래 get method의 경우에도 todo들이 들어있는 폴더(`todos/`) 내부의 {todoId}번 todo를 가져올거야! 정도로 생각하시면 판할거에요~!

2024-02-18 01:35 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/api/TodoController.java
> +		}
enum화 시키고 switch-case 문으로 바꿔주는 것도 좋아요~
이렇게 되면 soft나 hard 외의 다른 모든 문자는 hard delete를 해버리기 때문에 문제가 될 여지가 있어요~!

2024-02-18 01:35 UTC, mongmeo-dev commented on src/main/java/com/projectlyrics/onboarding/domain/todo/entity/Todo.java
> +	private boolean isDeleted;
엇 그렇군요!! 감사합니다 :)

2024-02-18 08:37 UTC, mongmeo-dev approved these changes
LGTM

2024-02-18 09:14 UTC, merged